export interface Archetype { id: number; name: string; description: string; wellnessBaseline: number; keyTraits: string[]; triggerPoints: string[]; color: string; icon: string; }
export const archetypes: Archetype[] = [
  { id: 1, name: "The Burnt-Out Professional", description: "High-achiever drowning in deadlines, surviving on delivery apps and caffeine.", wellnessBaseline: 55, keyTraits: ["Works 50+ hours/week", "Skips meals or stress-eats", "High screen time", "Poor sleep quality"], triggerPoints: ["Late-night DoorDash orders", "Skipping the gym", "Energy drink purchases"], color: "amber", icon: "\u{1F525}" },
  { id: 2, name: "The Former Athlete", description: "Once fit, now struggling as metabolism slows and old habits don't work.", wellnessBaseline: 65, keyTraits: ["Used to be very active", "Eating same portions but moving less", "Nostalgic about past fitness", "Prone to injuries"], triggerPoints: ["Large portion sizes", "Beer and sports drinks", "Skipping recovery days"], color: "green", icon: "\u{1F3C3}" },
  { id: 3, name: "The Overwhelmed Parent", description: "Putting everyone else first, grabbing whatever food is fast and easy.", wellnessBaseline: 50, keyTraits: ["Zero personal time", "Eats kids' leftovers", "Exhausted constantly", "Feels guilty about self-care"], triggerPoints: ["Drive-thru runs", "Snacking after kids sleep", "Skipping workouts for family needs"], color: "rose", icon: "\u{1F49B}" },
  { id: 4, name: "The Social Butterfly", description: "Life revolves around events, dinners, and drinks with friends.", wellnessBaseline: 60, keyTraits: ["Multiple social events weekly", "FOMO drives decisions", "Vulnerable to peer pressure", "Weekend warrior mentality"], triggerPoints: ["Group food orders", "Happy hour invitations", "Brunches"], color: "yellow", icon: "\u{1F60E}" },
  { id: 5, name: "The Night Owl", description: "Comes alive after dark, makes worst decisions between 10pm-2am.", wellnessBaseline: 58, keyTraits: ["Reversed sleep schedule", "Late-night snacker", "Peak productivity at night", "Mornings are the enemy"], triggerPoints: ["Midnight cravings", "Endless scrolling sessions", "Late gaming sessions"], color: "indigo", icon: "\u{1F319}" },
  { id: 6, name: "The Emotional Eater", description: "Food is comfort, reward, and coping mechanism all in one.", wellnessBaseline: 52, keyTraits: ["Eats feelings", "Reward = food", "Stress = snacks", "Cycles of guilt"], triggerPoints: ["Bad day comfort food", "Celebration meals", "Boredom eating"], color: "pink", icon: "\u{1FAC6}" },
  { id: 7, name: "The Serial Starter", description: "Has tried every diet, app, and program. Starts strong, fades fast.", wellnessBaseline: 55, keyTraits: ["Graveyard of diet apps", "Unused gym memberships", "High initial enthusiasm", "Quick to abandon"], triggerPoints: ["Last meal before the diet binges", "Endless research on new programs", "Equipment purchases"], color: "orange", icon: "\u{1F680}" },
  { id: 8, name: "The Mindless Grazer", description: "Doesn't overeat at meals but constantly nibbles throughout the day.", wellnessBaseline: 57, keyTraits: ["Never feels truly full", "Always snacking", "Loses track of intake", "Eats out of boredom"], triggerPoints: ["Frequent pantry visits", "Eating while cooking", "TV snacking", "Desk snacking"], color: "gray", icon: "\u{1F32C}\u{FE0F}" },
  { id: 9, name: "The Perfectionist Quitter", description: "One slip-up ruins everything. All or nothing mentality.", wellnessBaseline: 53, keyTraits: ["Rigid rules about food/exercise", "Binary thinking", "Extremely self-critical", "Restart Monday mentality"], triggerPoints: ["Ruined day binges", "Post-slip spirals", "Avoiding tracking after mistakes"], color: "slate", icon: "\u{1F4A0}" },
  { id: 10, name: "The Mindful Aspirant", description: "Already on the journey, needs tools to stay consistent and go deeper.", wellnessBaseline: 70, keyTraits: ["Health-conscious already", "Seeks balance", "Self-aware", "Ready to level up"], triggerPoints: ["Travel disruptions", "Busy work periods", "Challenging social situations"], color: "teal", icon: "\u{1F9D8}" },
];
