export type QuestionType = "open_text" | "single_choice" | "multi_select" | "slider";
export interface QuestionOption { label: string; value: string; }
export interface Question { id: number; part: 1 | 2; text: string; sensitiveText: string; type: QuestionType; options?: QuestionOption[]; sliderMin?: number; sliderMax?: number; sliderMinLabel?: string; sliderMaxLabel?: string; placeholder?: string; }
export const questions: Question[] = [
  { id: 1, part: 1, text: "Think back to a time when you felt most like yourself. What did a typical morning look like?", sensitiveText: "Think back to a time when things felt easier. What did a typical morning look like?", type: "open_text", placeholder: "Describe your morning routine back then..." },
  { id: 2, part: 1, text: "When you had free time back then, what did you actually do with it?", sensitiveText: "When you had free time, what did you find yourself drawn to?", type: "open_text", placeholder: "What did you enjoy doing..." },
  { id: 3, part: 1, text: "Which of these best describes how you used to recharge?", sensitiveText: "Which of these best describes what helped you feel rested?", type: "single_choice", options: [{ label: "Moving my body", value: "A" }, { label: "Being around people who energized me", value: "B" }, { label: "Quiet and stillness", value: "C" }, { label: "Creating or building something", value: "D" }, { label: "A mix of all of these", value: "E" }] },
  { id: 4, part: 1, text: "When you were at your most consistent, what did that feel like?", sensitiveText: "When things felt steady, what did that feel like?", type: "single_choice", options: [{ label: "Effortless", value: "A" }, { label: "Disciplined", value: "B" }, { label: "Social", value: "C" }, { label: "Environmental", value: "D" }] },
  { id: 5, part: 1, text: "What's something you did regularly that you've quietly stopped?", sensitiveText: "Is there something that has quietly faded from your routine?", type: "open_text", placeholder: "Something you've stopped doing..." },
  { id: 6, part: 1, text: "What was the part of your day you were most protective of?", sensitiveText: "Was there a part of your day that felt especially important?", type: "open_text", placeholder: "The part of your routine you protected..." },
  { id: 7, part: 1, text: "When you think about your average Tuesday now, what's the first feeling?", sensitiveText: "When you think about a typical day now, what feeling comes up?", type: "single_choice", options: [{ label: "Busy but okay", value: "A" }, { label: "Productive but hollow", value: "B" }, { label: "Tired in a way sleep doesn't fix", value: "C" }, { label: "Honestly, a bit lost", value: "D" }, { label: "Fine, I'm adapting", value: "E" }] },
  { id: 8, part: 2, text: "How much of your identity is tied to your job?", sensitiveText: "How much of how you see yourself is connected to work?", type: "slider", sliderMin: 0, sliderMax: 100, sliderMinLabel: "None of it", sliderMaxLabel: "Almost all of it" },
  { id: 9, part: 2, text: "When was the last time you did something purely because it felt good?", sensitiveText: "When was the last time you did something just for joy?", type: "single_choice", options: [{ label: "This week", value: "A" }, { label: "This month", value: "B" }, { label: "I can't remember", value: "C" }, { label: "I don't let myself do that", value: "D" }] },
  { id: 10, part: 2, text: "What's the first thing you reach for when stressed, tired, or bored?", sensitiveText: "When overwhelmed, what do you usually turn to?", type: "open_text", placeholder: "What do you reach for..." },
  { id: 11, part: 2, text: "Which patterns do you recognize in yourself right now?", sensitiveText: "Do any of these feel familiar? Select any that apply.", type: "multi_select", options: [{ label: "Busier than ever but feel less like myself", value: "busier_less_self" }, { label: "I know what I should do but don't", value: "know_dont_do" }, { label: "Stopped doing things I loved without deciding to", value: "stopped_without_deciding" }, { label: "I check my phone more than I'd like", value: "phone_checking" }, { label: "Performing a version of myself", value: "performing_self" }, { label: "I eat/spend/scroll differently at night", value: "night_different" }] },
  { id: 12, part: 2, text: "What time of day do you feel most like yourself?", sensitiveText: "Is there a time of day when you feel most at ease?", type: "single_choice", options: [{ label: "Morning", value: "A" }, { label: "Afternoon", value: "B" }, { label: "Evening", value: "C" }, { label: "Honestly, rarely", value: "D" }] },
  { id: 13, part: 2, text: "Is there a version of yourself that you miss?", sensitiveText: "Is there a part of yourself you'd like to reconnect with?", type: "open_text", placeholder: "What do you miss about yourself..." },
  { id: 14, part: 2, text: "What's genuinely different about your life now that makes old routines hard?", sensitiveText: "What's changed that makes old routines harder?", type: "open_text", placeholder: "What's changed..." },
];
